apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ark-test
  namespace: ark
spec:
  selector:
    matchLabels:
      run: ark-test
  serviceName: "ark-test"
  replicas: 1
  template:
    metadata:
      labels:
        run: ark-test
    spec:
      containers:
      - name: ark-test
        image: hermsi/ark-server
        imagePullPolicy: Always
        env:
          - name: ADMINPASSWORD
            value: "admin"
          - name: MAX_PLAYERS
            value: "10"
          - name: SESSIONNAME
            value: "k8s-ark"
          - name: SERVER_MAP
            value: "TheIsland"
          - name: SERVER_PASSWORD
            value: "welcome"
          - name: TZ
            value: "UK"
          - name: GAME_CLIENT_PORT
            value: "7777"
          - name: UDP_SOCKET_PORT
            value: "7778"
          - name: RCON_PORT
            value: "27020"
          - name: SERVER_LIST_PORT
            value: "27015"
        ports:
        - containerPort: 7777
          name: serverport
          protocol: UDP
        - containerPort: 7778
          name: raw
          protocol: UDP
        - containerPort: 27020
          name: rcon
          protocol: TCP
        - containerPort: 27015
          name: serverlist
          protocol: UDP
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
          limits:
            memory: "16Gi"
            cpu: "2"
        ports:
        - containerPort: 7777
          name: serverport
          protocol: UDP
        - containerPort: 7778
          name: raw
          protocol: UDP
        - containerPort: 27020
          name: rcon
          protocol: TCP
        - containerPort: 27015
          name: serverlist
          protocol: UDP
